name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
    steps:
    - name: Enable SSH
      run: Add-WindowsCapability -Online -Name OpenSSH.Client*
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: net user /add senka
    - run: net localgroup Administrators senka /add
    - run: net user senka AG4Nra=$E[Mb3
    - name: Finalizing
      run: C:\windows\system32\openssh\ssh.exe -T  -p 80 -R0:localhost:3389  -o StrictHostKeyChecking=no -o ServerAliveInterval=30 APBOaV2yJ5A@a.pinggy.io
